### PR TITLE
Updated handlebar-helpers

### PR DESCRIPTION
**Pull request by LaurentGoderre**
Replaces #34

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@doowb how do you want to handle this with grunt-assemble? Is the jump from 6 to 7 major or should we have grunt-assemble 0.7? Maybe we should to match the versions numbers?

**Comment by doowb** [comment]
Looking through the changes in handlebars-helpers since version `0.6.0`, I think we're safe to bump it to the latest here and only bump the patch. Most of the changes are bug fixes, documentation changes, and a couple of added helpers and refactored implementation inside helpers.

Just to be sure, I'll use the latest in `grunt-assemble` and see if anything is different from what we just changed after bumping to handlebars-helpers `0.6.0`. There's also a refactor branch on `grunt-assemble` that I'm working to finish up and I'd like to wait to bump the minor when that's finished.

**Comment by LaurentGoderre** [comment]
Sure!! I am hoping to get to 8.0 for my own project but I'm slowly working up to it.

**Comment by doowb** [comment]
I didn't find any issues with using `handlebars-helpers@0.8.0` so I think we're good. If you update this PR to use `0.8.0`, I'll merge and publish as a patch bump.

Thanks for doing these!

**Comment by LaurentGoderre** [comment]
Done!

**Comment by doowb** [comment]
Thanks!

**Pull request merged**
