### PR TITLE
update handlebars-helpers to 0.7.3

### PR DESCRIPTION
**Pull request by dvera123**
update handlebars-helpers to 0.7.3

### CODE REVIEW

**Comment by jonschlinkert** [comment]
I think we'll need to get unit tests in this lib before merging any changes in. This should have been done earlier, we don't publish anything without tests now. I can leave this open in case someone wants to do a pr

**Comment by LaurentGoderre** [comment]
@jonschlinkert There is practically no code though...it's just an association of handlebars and helpers.

**Comment by LaurentGoderre** [comment]
This isn't as straightforward as it looks this would actually break it, I just found out

**Comment by jonschlinkert** [comment]
there are some nuances we need to address. We're getting there slowly but surely, all help is appreciated

**Comment by LaurentGoderre** [comment]
Closing in favor of #39

**Pull request closed without merging**
