### PR TITLE
Update to Handlebars 3.0.0

### PR DESCRIPTION
**Pull request by spacedawwwg**

### CODE REVIEW

**Comment by brunowego** [comment]
+1

**Comment by JDillon522** [comment]
@spacedawwwg or someone else: Try triggering the travis ci build again. There is absolutely no reason this should not pass. For redundancy's sake I forked it and tested it locally and its fine. I'd really like the ability to use some of Handlebar's 2.0 features with my assemble projects.

**Comment by jonschlinkert** [comment]
It looks like it's just node.js 0.8 failing. @doowb I don't have a problem merging this. We can also update travis, there is no reason to continue supporting 0.8

**Comment by jonschlinkert** [comment]
done! (cross your fingers! :)

**Comment by brunowego** [comment]
new tag? :package:

**Comment by brunowego** [comment]
Thanks :+1:

**Comment by jonschlinkert** [comment]
no prob, please let me know asap if this causes issues. Also @doowb brought up something. we might need to also bump the handlebars version in the 0.5.x version of handlebars-helpers. I just got back from vacation and haven't looked yet. If someone else wants to expedite and look into it that would be great. If it does need to be bumped there, we'll need to make sure all tests are passing too.

**Comment by JDillon522** [comment]
FYI I made a PR to update the handlebar-helpers [here](https://github.com/assemble/handlebars-helpers/issues/185)

**Pull request merged**
